export enum CoreErrorCode {
  VALIDATION_ERROR = "VALIDATION_ERROR",
  MARKET_NOT_FOUND = "MARKET_NOT_FOUND",
  MARKET_NOT_ACTIVE = "MARKET_NOT_ACTIVE",
  INVALID_TICK_SIZE = "INVALID_TICK_SIZE",
  INVALID_LOT_SIZE = "INVALID_LOT_SIZE",
  INVALID_PRICE = "INVALID_PRICE",
  INVALID_QUANTITY = "INVALID_QUANTITY",
  INVALID_ORDER = "INVALID_ORDER",
}
